### ISSUE TITLE
Investigate 404 errors

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#272]
### Description

In prod, we're getting 10 mysterious 404s every 5 minutes

First, work with CDT to resolve the "we can't investigate in Application Insights because it times out when drilling down" issue.

### Acceptance Criteria

- [ ] Write up an explanation for the 404s.

**Comment by kalvinwang** [comment]
Timeouts resolved last week so this is now unblocked

**Comment by rocketnova** [comment]
We were getting 10 404s every 5 minutes ('GET \') in all environments except for staging. It turns out that this comes from the "Always On" feature of Azure App Service. From [Configure an App Service app in the Azure portal: Configure general settings](https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-general-settings):
> Always On: Keeps the app loaded even when there's no traffic. When Always On is not turned on (default), the app is unloaded after 20 minutes without any incoming requests. The unloaded app can cause high latency for new requests because of its warm-up time. When Always On is turned on, the front-end load balancer sends a GET request to the application root every five minutes. The continuous ping prevents the app from being unloaded.

I have disabled the "Always On" feature in all of the Azure environments now that we have #213
