### ISSUE TITLE
Investigate server request traffic

### ISSUE THREAD

**Issue by kalvinwang** [cagov/ui-claim-tracker#473]
### Description

We had 1.66M server requests in the first 6 hours of traffic, vs about 10% of that in terms of API gateway requests/responses. Should there be 10 server requests per page load? Is something not being cached that should be?

### Acceptance Criteria

- [ ] Investigate and determine what next steps to take if any

**Comment by rocketnova** [comment]
We reviewed a few samples of 24h of data and the Next.js documentation. A single request to `/claimstatus` will trigger dependent requests for additional supporting assets. These include various client-side javascript chunks, css files, static assets in /public, and json data files. Next.js [generates etags](https://nextjs.org/docs/api-reference/next.config.js/disabling-etag-generation) for all pages by default and automatically [adds caching headers](https://github.com/vercel/next.js/blob/1a9492d51fdad92a833e89e65b9510698c69b634/docs/going-to-production.md#caching) to

> immutable assets served from /_next/static including JavaScript, CSS, static images, and other media.

Cache control is set to `Cache-Control: public, max-age=31536000, immutable` for everything inside `/_next/static` (see details of [immutable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#revalidation_and_reloading)). Based on [caching principles](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching), we would expect most `/_next/static` resources to not require revalidation since `max-age` is set to 1 year. However, we're seeing ~50% of resource requests being sent 304 responses, which indicates the browser sent a revalidation request. This is likely due to [individual browser revalidation policies](https://stackoverflow.com/questions/45829055/why-doesnt-chrome-re-validate-in-memory-cache-when-doing-a-normal-reload) (i.e. cases where particular browsers will revalidate before expiration, such as when the user clicks the refresh button), so we are not going to continue investigating at this time.

Assets outside `/_next/static` (i.e. images, favicon, json data), have `max-age=0`, so the browser will always revalidate those right now. In the future, we could pursue a strategy to sets `max-age` to something larger and handles etags.

According to Next.js documentation, we could choose to use a [CDN](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix) to serve all assets in `/_next/static` by adding the `assetPrefix` config to next.config.js and uploading assets to the CDN. If we wanted to configure the CDN to serve `/public` and `/data`, we would need to update the urls for those assets in the code, in addition to uploading the assets to the CDN.

It's unclear why the en.json and es.json files are requests so much less frequently than the other assets. In our testing, we found that requests for the json files is not tied to Scenario 2. Because the behaviour is working as desired and the requests are so infrequent, we decided not to continue investigating at this time.
