### ISSUE TITLE
Prepare status content for prototype testing

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#60]
### Description
Go deep on status content for prototype testing

### Scenarios

1. Benefit year ending soon
2. In the queue for EDD review

### Acceptance Criteria

  - [x] Identify which claim status to build out for prototype
  - [x] Content is written and ready for testing

**Comment by AngelQuicksey** [comment]
@nicoleslaw Can you break out "develop content model/structure" into a separate ticket (or tickets, if neessary)? This/these should have it's/their own acceptance criteria. We can keep this ticket and downgrade the size. My thought is, if we have more detail, we can better track what's truly in progress and what's blocked.

**Comment by nicoleslaw** [comment]
Diana and I are pairing today on the scenarios and documentation so far. I should have a direction here by the end of the sprint.

**Comment by nicoleslaw** [comment]
I've mocked up content for a few scenarios so far, but we still need to narrow in on priority scenarios in the next sprint.

- No claim yet (empty state)
- Claim on hold: eligibility issue
- Claim on hold: ID documentation required

**Comment by nicoleslaw** [comment]
Given our conversations this week, here are the scenarios I am thinking we should mock up. At the moment, I would like to test the ones with a star (*) but we need to discuss as a team.

- Expiring soon*
- Expired (similar but slightly different variation)
- On extension
- In the queue for EDD triage*
- Pending ID verification steps from the claimant*

**Comment by nicoleslaw** [comment]
I took a shot [here](https://docs.google.com/document/d/18_efJxutY7gU_mWQ5xmxug8WXCx7fjyLSMcHQObA-NM/edit#)...and went off script a little bit. I am having a hard time not using the next steps header for clarity, structure, and scannability. Every heading is titlecase now.

My main questions for discussion are:

- If we're only focused on last/current/next steps, can we frame that around payment instead of claim status?
- Can we only show extension info if it applies?
- Can we specify the claimant's email and phone info so they can confirm it on this screen, and then link out to the appropriate UIO screen to update it?

Open to your thoughts!

cc @dianagriffin @nguyen-tina @JessiBull

**Comment by nicoleslaw** [comment]
We may need to revisit our scenarios for testing, but the content I prepped is ready for testing. I will close this and open more specific tickets as we figure out next steps.
