### ISSUE TITLE
Optimization: Implement JSON Web Tokens to provide "logged-in" experience 

### ISSUE THREAD

**Issue by kevmo** [cagov/ui-claim-tracker#83]
### Description

The authentication strategy for Claims Tracker Minimum Viable Product requires the use of SAML only.  Unfortunately, this requires SAML auth for every single page view (costly in both terms of time and computer resources). Once more details about the length of user authentication persistence is known, we can implement JWTs to provide a logged-in experience (i.e. user is not required to log in for X amount of time).

To implement this:
- Add middleware to check every request for a JWT 
- Every request should have a JWT. 
- If no JWT, SAML flow should be kicked off & user redirected to BPO SSO URL.
- If JWT, render logged-in UX. 
- SAML assertions authenticated at `/acs` URL should result in JWT being created.

Once more information is known about the scope and validity of this optimization, these items should probably be broken into separate tickets. 

### Acceptance Criteria

  - [ ] Determine whether JWTs should be used.
  - [ ] Break this ticket into more detailed tickets if previous criteria answered in affirmative.

**Comment by kalvinwang** [comment]
This may already be covered by the bullets in the summary, but pasting David's proposed steps including JWT here since I'm removing from the main doc:

- Select an authentication library supporting SAML and add it to the project 
- First idea: consider using Passport
- Decide on a strategy for checking whether a user is authenticated
- First idea: expect an `Authorization: Bearer <xxx>` header where the bearer token is a JSON Web Token (JWT) (or other opaque token) that Claim Tracker generates
- Add middleware that protects routes from unauthenticated clients and can respond with an HTTP redirect if they aren't logged in
- Middleware will eventually check whether each requests meets the criteria defined in #2. For now it will have placeholder logic to be updated in step #9. 
- Configure redirection: when a user is not logged in, redirect to the SAML "http redirect" binding URL contained in the SAML metadata file
- Some SAML libraries can parse the metadata file directly and expose a method like "GetSSOBindingLocation(HTTPRedirectBinding)". Use the library from #1 to determine the best way to do this, or do it by hand
- During redirection, a unique random string should be generated as part of the request. This must be tracked and correlated with a value received when the user returns from the SSO login in a later step. Determine whether the library from #1 does this automatically or if we need to manually configure it. 
- Note: this removes the "unsolicited login" option that some SAML IDP's support. Unsolicited login is when the IDP shows a list of possible/supported SPs to navigate to after a user logs into the IDP. We don’t think we’ll need to support this feature
- Add an endpoint for the SAML IDP to POST its response assertions to. Typically this is something like "/saml/acs". 
- Depending on the library chosen, this may be handled automatically.
- Add validation logic for SAML assertions received
- Depending on the library chosen, this may be handled automatically
- Ensure that assertion is signed with BPO's public key, that it contains the request ID from #4b, that it is addressed to claim tracker, and that it is not expired.
- Add function to generate an opaque token from a received SAML assertion.
- First idea: use a JWT
- The token should contain at least a field for issuer (which is the claim tracker), a NBF date (not before…), an expiration date, and the "Unique Number" from BPO which will be in the SAML assertion from #5.
- Wire up JWT generation: when a new SAML assertion is received at the endpoint in #5 and validated by the logic in #6, then the token should be generated automatically and returned to the client along with a redirect back to Claim Tracker's main page.
- Update middleware created in #3 to work correctly with the tokens generated in #7.
- If a JWT is used, this is where we'd want to check the decryption key, issuer, expiration/nbf dates, etc.
- Validate that the cycle is complete: the token returned by #8 should be accepted by the middleware in #2 and allow a "logged in" experience.
-

**Comment by kalvinwang** [comment]
Closing #80, #81, #82, #83 since we're switching to the IDM team's proxy authentication approach. Can re-open if ever needed.
